### ISSUE TITLE
[Bug]: Can't put saddle/horse armor on tamed horse

### ISSUE THREAD

**Issue by LoriKat** [Fyoncle/Elysium-Days#10]
### Important Steps

- [X] I have checked that theres no other similar issue opened about this bug.
- [X] I have checked the Known Issues & Fixes on the Wiki and my issue is not stated there.

### Modpack Version

3.6.0 / Fabric 1.20.1

### Bug Description

I was experimenting with this modpack in Creative mode, and I tamed a horse and tried putting a saddle on it. However, when I try to open the horse's menu, it only shows my inventory menu. Right-click and Shift + right click on the horse don't work either. I tried the same on a donkey, but I can only give it a chest, no saddle. I also changed my gamemode into survival, same issue.

### Steps to reproduce

1. Create new world (I was on creative)
2. Spawn a horse/donkey (or find one)
3. Tame horse/donkey
4. Get saddle from creative menu
5. Try to open horse's menu (Right-click to ride horse and press E _OR_ Shift+right click on horse)
6. See only player's menu

**Comment by Fyoncle** [comment]
Hello!

**Comment by Fyoncle** [comment]
You have to click only E instead of CTRL + E, other than that, i cannot reproduce this issue. Horses are wokring fine for me, did u add any other mods?

**Comment by LoriKat** [comment]
Oh, I just reinstalled the modpack and now it works!

**Comment by Fyoncle** [comment]
> Oh, I just reinstalled the modpack and now it works!

Glad to hear it worked for you, if you don't have any other issues u can close the issue!

**Comment by LoriKat** [comment]
Okay, thank you!

**Comment by Fyoncle** [comment]
> Okay, thank you!

You're welcome, always! ❤️

**Comment by Fyoncle** [comment]
Hey @LoriKat That issue was caused if you have sprint key on toggle, FYI.
