### ISSUE TITLE
[Bug]: textures are weird??

### ISSUE THREAD

**Issue by radsic** [Fyoncle/Elysium-Days#12]
### Important Steps

- [X] I have checked that theres no other similar issue opened about this bug.
- [X] I have checked the Known Issues & Fixes on the Wiki and my issue is not stated there.

### Modpack Version

1.20.1

### Bug Description

When I first downloaded this pack, I loaded in and there were bed textures ALL over the floor, and I thought it was maybe a biome thing.. when I went to the ocean and saw the purple bed textures in the ocean. You can't even sleep in them, they are all just meshes of purple beds, and additionally; when I put down a crafting table, it was not a crafting table block. It was a line of redstone.. Please let me know what is happening and how to fix it.

### Steps to reproduce

1. Install mod pack to 1.20.1 fabric after changing it to a zip file to play in a server. (by the way, I ONLY added the mods from the zip not anything else.)
2. load into server
3. see beds everywhere

**Comment by Fyoncle** [comment]
You didn't read the known issues wiki, that's because you opened a vanilla server for a fabric modpack.
