### ISSUE TITLE
[Linux Crash]: Elysium Days Tweaks triggering Segfault on launch (SIGSEV)

### ISSUE THREAD

**Issue by ItsShamed** [Fyoncle/Elysium-Days#14]
### Important Steps

- [X] I have checked that theres no other similar issue opened about this bug.
- [X] I have checked the Known Issues & Fixes on the Wiki and my issue is not stated there.

### Modpack Version

6.0.0

### Bug Description

When Elysium Days Tweaks tries to set the window icon, it segfaults and immediately crashes the game at startup.
For reference: I am on NixOS 24.05, and I'm using Prism Launcher

### Steps to reproduce

1. Install Elysium Days
2. Launch
3. Crash

### Log File

https://mclo.gs/y6E2FAb

**Comment by Fyoncle** [comment]
I don't use linux so i have no idea how can i go on testing the fix, do you have discord? so we can test the fix ill do tomorrow before releasing.

**Comment by VipCoder8** [comment]
I'm not quite sure what can be the problem, but issue is probably related to your OS.

**Comment by Fyoncle** [comment]
Will be fixed with 6.1.0
