### ISSUE TITLE
[Linux Crash]: Modpack launches but crashes before showing the menu

### ISSUE THREAD

**Issue by Rokiiz** [Fyoncle/Elysium-Days#15]
### Important Steps

- [X] I have checked that theres no other similar issue opened about this bug.
- [X] I have checked the Known Issues & Fixes on the Wiki and my issue is not stated there.

### Modpack Version

6.0.0

### Bug Description

when launching the game, minecraft opens and shows a black screen, after a bit the game crashes still showing a black screen.

The [Relase 5.3.0](https://github.com/Fyoncle/Elysium-Days/releases/tag/5.3.0) works with no issue, so I am using this for the time being.

I am in Arch Linux and using Prism Launcher.

### Steps to reproduce

1. Install Elysium 6.0.0
2. Launch
3. results in a Crash

### Log File

https://mclo.gs/IB596gc

**Comment by Rokiiz** [comment]
what pops up in the log file is `X Error of failed request:  BadLength (poly request too large or internal Xlib length error)`.
the [major fix](https://github.com/LukeSmithxyz/st/issues/130#issuecomment-1008550245) I have seen for this is to install a package called `bdf-unifont` or `unifont` which has helped for different programs but had no effect for me.

**Comment by Fyoncle** [comment]
Duplicate of https://github.com/Fyoncle/Elysium-Days/issues/14 probably.

Already fixed in the dev version.

If you wanna try the jar file yourself to make sure it's not a different issue and fixed it's fixed for you, please contact me on [Discord](https://discord.gg/WFpDr7zY8Z)!

**Comment by Fyoncle** [comment]
@Rokiiz Do you have discord?

**Comment by Rokiiz** [comment]
> @Rokiiz Do you have discord?

I do, I'll join now.

**Comment by Fyoncle** [comment]
> > @Rokiiz Do you have discord?
> 
> I do, I'll join now.

Thanks ❤️
